# Generated by Django 5.0 on 2023-12-16 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_alter_project_steps_service_step'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='services',
        ),
        migrations.RemoveField(
            model_name='project',
            name='steps',
        ),
    ]
