# Generated by Django 4.1.7 on 2023-12-18 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_remove_project_services_remove_project_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='short_description',
            field=models.TextField(default='shortdesc'),
            preserve_default=False,
        ),
    ]
