# Generated by Django 5.0 on 2023-12-18 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_project_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='banner_image',
            field=models.ImageField(null=True, upload_to='content/'),
        ),
        migrations.AddField(
            model_name='project',
            name='main_image',
            field=models.ImageField(null=True, upload_to='content/'),
        ),
        migrations.AddField(
            model_name='project',
            name='secondary_image',
            field=models.ImageField(null=True, upload_to='content/'),
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(null=True, upload_to='content/'),
        ),
    ]
