# Generated by Django 5.0 on 2023-12-18 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_project_banner_image_project_main_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='banner_image',
            field=models.ImageField(null=True, upload_to='img/content/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='main_image',
            field=models.ImageField(null=True, upload_to='img/content/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='secondary_image',
            field=models.ImageField(null=True, upload_to='img/content/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(null=True, upload_to='img/content/'),
        ),
    ]
