# Generated by Django 4.1.7 on 2023-03-07 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('num_adults', models.IntegerField()),
                ('num_children', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('image', models.ImageField(blank=True, null=True, upload_to='city_images')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.city')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cuisine', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='hotel_images')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.city')),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='tour_images/')),
                ('bookings', models.ManyToManyField(blank=True, to='tours.booking')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.city')),
                ('hotels', models.ManyToManyField(to='tours.hotel')),
                ('restaurants', models.ManyToManyField(to='tours.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Entertainment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='restaurant_images')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.city')),
            ],
        ),
        migrations.CreateModel(
            name='BookingRestaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.booking')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='BookingEntertainment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.booking')),
                ('entertainment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.entertainment')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='entertainment_choices',
            field=models.ManyToManyField(blank=True, through='tours.BookingEntertainment', to='tours.entertainment'),
        ),
        migrations.AddField(
            model_name='booking',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.hotel'),
        ),
        migrations.AddField(
            model_name='booking',
            name='restaurant_choices',
            field=models.ManyToManyField(blank=True, through='tours.BookingRestaurant', to='tours.restaurant'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
